# Generated by Django 4.1.6 on 2023-02-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_has_confirmed_confirmstring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmstring',
            options={'ordering': ['-c_time'], 'verbose_name': '确认码', 'verbose_name_plural': '确认码'},
        ),
    ]
